spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: akhd0416

server:
    servlet:
        context-path: /ex-bbs
